-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ufunc_call_i4_sqrt_fixed_32_32_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of ufunc_call_i4_sqrt_fixed_32_32_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal x_read_reg_1492 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal x_read_reg_1492_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal x_read_reg_1492_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal x_read_reg_1492_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal x_read_reg_1492_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal x_read_reg_1492_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal x_read_reg_1492_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal x_l_I_V_32_fu_346_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_l_I_V_32_reg_1497 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_33_fu_354_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_33_reg_1503 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln443_2_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln443_2_reg_1509 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln202_1_fu_400_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln202_1_reg_1515 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_l_I_V_34_fu_503_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_l_I_V_34_reg_1520 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_35_fu_511_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_35_reg_1526 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln443_4_fu_551_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln443_4_reg_1532 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln202_3_fu_557_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln202_3_reg_1538 : STD_LOGIC_VECTOR (6 downto 0);
    signal x_l_I_V_36_fu_660_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_l_I_V_36_reg_1543 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_37_fu_668_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_37_reg_1549 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln443_6_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln443_6_reg_1555 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln202_5_fu_714_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln202_5_reg_1561 : STD_LOGIC_VECTOR (8 downto 0);
    signal x_l_I_V_37_fu_817_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_l_I_V_37_reg_1566 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_fu_825_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_reg_1572 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln443_8_fu_865_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln443_8_reg_1578 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln202_7_fu_871_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln202_7_reg_1584 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_l_I_V_40_fu_1056_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_l_I_V_40_reg_1589 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_41_fu_1064_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_41_reg_1595 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_31_reg_1601 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_81_reg_1606 : STD_LOGIC_VECTOR (13 downto 0);
    signal x_l_I_V_42_fu_1213_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_l_I_V_42_reg_1612 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_43_fu_1221_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_43_reg_1618 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_37_reg_1624 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_87_reg_1629 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_l_I_V_44_fu_1370_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_l_I_V_44_reg_1635 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_45_fu_1378_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_45_reg_1641 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_93_fu_1386_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_93_reg_1648 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_fu_226_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln202_fu_242_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln657_fu_222_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln202_fu_246_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln443_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_50_fu_252_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_32_fu_272_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_71_fu_280_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal x_l_I_V_31_fu_264_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_1_fu_290_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_51_fu_298_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln443_fu_308_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln202_fu_318_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln443_1_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_52_fu_324_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_53_fu_336_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_4_fu_362_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_372_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_54_fu_380_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln443_1_fu_390_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_55_fu_406_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_56_fu_416_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_34_fu_431_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_8_fu_437_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_l_I_V_33_fu_425_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_3_fu_447_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_57_fu_455_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln443_2_fu_465_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln202_2_fu_475_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln443_3_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_58_fu_481_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_59_fu_493_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_10_fu_519_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_fu_529_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_60_fu_537_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln443_3_fu_547_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_61_fu_563_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_62_fu_573_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_36_fu_588_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_13_fu_594_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_l_I_V_35_fu_582_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_5_fu_604_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_63_fu_612_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln443_4_fu_622_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln202_4_fu_632_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln443_5_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_64_fu_638_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_65_fu_650_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_16_fu_676_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_6_fu_686_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_66_fu_694_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln443_5_fu_704_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_67_fu_720_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_68_fu_730_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_38_fu_745_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_19_fu_751_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_l_I_V_fu_739_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_7_fu_761_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_69_fu_769_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln443_6_fu_779_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln202_6_fu_789_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln443_7_fu_783_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_70_fu_795_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_71_fu_807_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_22_fu_833_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_843_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Result_72_fu_851_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln443_7_fu_861_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_73_fu_877_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_74_fu_887_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_39_fu_902_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_25_fu_908_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_l_I_V_38_fu_896_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_9_fu_918_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_75_fu_926_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln443_8_fu_936_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln202_8_fu_946_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln443_9_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_76_fu_952_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_77_fu_964_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_40_fu_982_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_28_fu_990_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_l_I_V_39_fu_974_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_s_fu_1000_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_78_fu_1008_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln443_9_fu_1018_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln202_9_fu_1028_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln443_10_fu_1022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_79_fu_1034_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_80_fu_1046_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_fu_1092_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln443_10_fu_1099_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln202_10_fu_1108_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln443_11_fu_1103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_82_fu_1113_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_83_fu_1124_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_42_fu_1140_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_34_fu_1147_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal x_l_I_V_41_fu_1133_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_11_fu_1157_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_84_fu_1165_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln443_11_fu_1175_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln202_11_fu_1185_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln443_12_fu_1179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_85_fu_1191_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_86_fu_1203_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_fu_1249_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln443_12_fu_1256_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln202_12_fu_1265_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln443_13_fu_1260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_88_fu_1270_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_89_fu_1281_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_44_fu_1297_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_40_fu_1304_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal x_l_I_V_43_fu_1290_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_13_fu_1314_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_90_fu_1322_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln443_13_fu_1332_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln202_13_fu_1342_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln443_14_fu_1336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_91_fu_1348_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_92_fu_1360_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_14_fu_1397_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln443_14_fu_1404_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln202_14_fu_1413_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln443_15_fu_1408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_94_fu_1418_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_95_fu_1429_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_46_fu_1445_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_I_V_fu_1452_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal x_l_I_V_45_fu_1438_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal zext_ln662_fu_1460_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_48_fu_1464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_I_V_30_fu_1470_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_1390_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_I_V_47_fu_1476_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln53_fu_1484_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal x_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (15 downto 0);


begin




    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= select_ln53_fu_1484_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                icmp_ln443_2_reg_1509 <= icmp_ln443_2_fu_394_p2;
                icmp_ln443_4_reg_1532 <= icmp_ln443_4_fu_551_p2;
                icmp_ln443_6_reg_1555 <= icmp_ln443_6_fu_708_p2;
                icmp_ln443_8_reg_1578 <= icmp_ln443_8_fu_865_p2;
                p_Result_31_reg_1601 <= res_I_V_41_fu_1064_p3(15 downto 4);
                p_Result_37_reg_1624 <= res_I_V_43_fu_1221_p3(15 downto 2);
                p_Result_81_reg_1606 <= x_l_I_V_40_fu_1056_p3(21 downto 8);
                p_Result_87_reg_1629 <= x_l_I_V_42_fu_1213_p3(19 downto 4);
                p_Result_93_reg_1648 <= p_Result_93_fu_1386_p1;
                res_I_V_33_reg_1503 <= res_I_V_33_fu_354_p3;
                res_I_V_35_reg_1526 <= res_I_V_35_fu_511_p3;
                res_I_V_37_reg_1549 <= res_I_V_37_fu_668_p3;
                res_I_V_41_reg_1595 <= res_I_V_41_fu_1064_p3;
                res_I_V_43_reg_1618 <= res_I_V_43_fu_1221_p3;
                res_I_V_45_reg_1641 <= res_I_V_45_fu_1378_p3;
                res_I_V_reg_1572 <= res_I_V_fu_825_p3;
                sub_ln202_1_reg_1515 <= sub_ln202_1_fu_400_p2;
                sub_ln202_3_reg_1538 <= sub_ln202_3_fu_557_p2;
                sub_ln202_5_reg_1561 <= sub_ln202_5_fu_714_p2;
                sub_ln202_7_reg_1584 <= sub_ln202_7_fu_871_p2;
                x_l_I_V_32_reg_1497 <= x_l_I_V_32_fu_346_p3;
                x_l_I_V_34_reg_1520 <= x_l_I_V_34_fu_503_p3;
                x_l_I_V_36_reg_1543 <= x_l_I_V_36_fu_660_p3;
                x_l_I_V_37_reg_1566 <= x_l_I_V_37_fu_817_p3;
                x_l_I_V_40_reg_1589 <= x_l_I_V_40_fu_1056_p3;
                x_l_I_V_42_reg_1612 <= x_l_I_V_42_fu_1213_p3;
                x_l_I_V_44_reg_1635 <= x_l_I_V_44_fu_1370_p3;
                x_read_reg_1492 <= x_int_reg;
                x_read_reg_1492_pp0_iter1_reg <= x_read_reg_1492;
                x_read_reg_1492_pp0_iter2_reg <= x_read_reg_1492_pp0_iter1_reg;
                x_read_reg_1492_pp0_iter3_reg <= x_read_reg_1492_pp0_iter2_reg;
                x_read_reg_1492_pp0_iter4_reg <= x_read_reg_1492_pp0_iter3_reg;
                x_read_reg_1492_pp0_iter5_reg <= x_read_reg_1492_pp0_iter4_reg;
                x_read_reg_1492_pp0_iter6_reg <= x_read_reg_1492_pp0_iter5_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_int_reg <= x;
            end if;
        end if;
    end process;
    add_ln202_fu_246_p2 <= std_logic_vector(unsigned(zext_ln202_fu_242_p1) + unsigned(ap_const_lv3_7));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(select_ln53_fu_1484_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= select_ln53_fu_1484_p3;
        end if; 
    end process;

    icmp_ln443_10_fu_1022_p2 <= "1" when (unsigned(p_Result_78_fu_1008_p4) < unsigned(zext_ln443_9_fu_1018_p1)) else "0";
    icmp_ln443_11_fu_1103_p2 <= "1" when (unsigned(p_Result_81_reg_1606) < unsigned(zext_ln443_10_fu_1099_p1)) else "0";
    icmp_ln443_12_fu_1179_p2 <= "1" when (unsigned(p_Result_84_fu_1165_p4) < unsigned(zext_ln443_11_fu_1175_p1)) else "0";
    icmp_ln443_13_fu_1260_p2 <= "1" when (unsigned(p_Result_87_reg_1629) < unsigned(zext_ln443_12_fu_1256_p1)) else "0";
    icmp_ln443_14_fu_1336_p2 <= "1" when (unsigned(p_Result_90_fu_1322_p4) < unsigned(zext_ln443_13_fu_1332_p1)) else "0";
    icmp_ln443_15_fu_1408_p2 <= "1" when (unsigned(p_Result_93_reg_1648) < unsigned(zext_ln443_14_fu_1404_p1)) else "0";
    icmp_ln443_1_fu_312_p2 <= "1" when (unsigned(p_Result_51_fu_298_p4) < unsigned(zext_ln443_fu_308_p1)) else "0";
    icmp_ln443_2_fu_394_p2 <= "1" when (unsigned(p_Result_54_fu_380_p4) < unsigned(zext_ln443_1_fu_390_p1)) else "0";
    icmp_ln443_3_fu_469_p2 <= "1" when (unsigned(p_Result_57_fu_455_p4) < unsigned(zext_ln443_2_fu_465_p1)) else "0";
    icmp_ln443_4_fu_551_p2 <= "1" when (unsigned(p_Result_60_fu_537_p4) < unsigned(zext_ln443_3_fu_547_p1)) else "0";
    icmp_ln443_5_fu_626_p2 <= "1" when (unsigned(p_Result_63_fu_612_p4) < unsigned(zext_ln443_4_fu_622_p1)) else "0";
    icmp_ln443_6_fu_708_p2 <= "1" when (unsigned(p_Result_66_fu_694_p4) < unsigned(zext_ln443_5_fu_704_p1)) else "0";
    icmp_ln443_7_fu_783_p2 <= "1" when (unsigned(p_Result_69_fu_769_p4) < unsigned(zext_ln443_6_fu_779_p1)) else "0";
    icmp_ln443_8_fu_865_p2 <= "1" when (unsigned(p_Result_72_fu_851_p4) < unsigned(zext_ln443_7_fu_861_p1)) else "0";
    icmp_ln443_9_fu_940_p2 <= "1" when (unsigned(p_Result_75_fu_926_p4) < unsigned(zext_ln443_8_fu_936_p1)) else "0";
    icmp_ln443_fu_236_p2 <= "1" when (tmp_fu_226_p4 = ap_const_lv2_0) else "0";
    mul_I_V_fu_1452_p3 <= (ap_const_lv17_0 & res_I_V_46_fu_1445_p3);
    p_Result_10_fu_519_p4 <= res_I_V_35_fu_511_p3(15 downto 11);
    p_Result_13_fu_594_p4 <= res_I_V_36_fu_588_p3(15 downto 10);
    p_Result_16_fu_676_p4 <= res_I_V_37_fu_668_p3(15 downto 9);
    p_Result_19_fu_751_p4 <= res_I_V_38_fu_745_p3(15 downto 8);
    p_Result_22_fu_833_p4 <= res_I_V_fu_825_p3(15 downto 7);
    p_Result_25_fu_908_p4 <= res_I_V_39_fu_902_p3(15 downto 6);
    p_Result_28_fu_990_p4 <= res_I_V_40_fu_982_p3(15 downto 5);
    p_Result_34_fu_1147_p4 <= res_I_V_42_fu_1140_p3(15 downto 3);
    p_Result_40_fu_1304_p4 <= res_I_V_44_fu_1297_p3(15 downto 1);
    p_Result_48_fu_1464_p2 <= "1" when (unsigned(x_l_I_V_45_fu_1438_p3) > unsigned(zext_ln662_fu_1460_p1)) else "0";
    p_Result_4_fu_362_p4 <= res_I_V_33_fu_354_p3(15 downto 13);
    p_Result_50_fu_252_p5 <= (zext_ln657_fu_222_p1(34 downto 33) & add_ln202_fu_246_p2 & zext_ln657_fu_222_p1(29 downto 0));
    p_Result_51_fu_298_p4 <= x_l_I_V_31_fu_264_p3(31 downto 28);
    p_Result_52_fu_324_p5 <= (x_l_I_V_31_fu_264_p3(34 downto 32) & sub_ln202_fu_318_p2 & x_l_I_V_31_fu_264_p3(27 downto 0));
    
    p_Result_53_fu_336_p4_proc : process(res_I_V_32_fu_272_p3)
    begin
        p_Result_53_fu_336_p4 <= res_I_V_32_fu_272_p3;
        p_Result_53_fu_336_p4(14) <= ap_const_lv1_1(0);
    end process;

    p_Result_54_fu_380_p4 <= x_l_I_V_32_fu_346_p3(30 downto 26);
    p_Result_55_fu_406_p5 <= (x_l_I_V_32_reg_1497(34 downto 31) & sub_ln202_1_reg_1515 & x_l_I_V_32_reg_1497(25 downto 0));
    
    p_Result_56_fu_416_p4_proc : process(res_I_V_33_reg_1503)
    begin
        p_Result_56_fu_416_p4 <= res_I_V_33_reg_1503;
        p_Result_56_fu_416_p4(13) <= ap_const_lv1_1(0);
    end process;

    p_Result_57_fu_455_p4 <= x_l_I_V_33_fu_425_p3(29 downto 24);
    p_Result_58_fu_481_p5 <= (x_l_I_V_33_fu_425_p3(34 downto 30) & sub_ln202_2_fu_475_p2 & x_l_I_V_33_fu_425_p3(23 downto 0));
    
    p_Result_59_fu_493_p4_proc : process(res_I_V_34_fu_431_p3)
    begin
        p_Result_59_fu_493_p4 <= res_I_V_34_fu_431_p3;
        p_Result_59_fu_493_p4(12) <= ap_const_lv1_1(0);
    end process;

    p_Result_60_fu_537_p4 <= x_l_I_V_34_fu_503_p3(28 downto 22);
    p_Result_61_fu_563_p5 <= (x_l_I_V_34_reg_1520(34 downto 29) & sub_ln202_3_reg_1538 & x_l_I_V_34_reg_1520(21 downto 0));
    
    p_Result_62_fu_573_p4_proc : process(res_I_V_35_reg_1526)
    begin
        p_Result_62_fu_573_p4 <= res_I_V_35_reg_1526;
        p_Result_62_fu_573_p4(11) <= ap_const_lv1_1(0);
    end process;

    p_Result_63_fu_612_p4 <= x_l_I_V_35_fu_582_p3(27 downto 20);
    p_Result_64_fu_638_p5 <= (x_l_I_V_35_fu_582_p3(34 downto 28) & sub_ln202_4_fu_632_p2 & x_l_I_V_35_fu_582_p3(19 downto 0));
    
    p_Result_65_fu_650_p4_proc : process(res_I_V_36_fu_588_p3)
    begin
        p_Result_65_fu_650_p4 <= res_I_V_36_fu_588_p3;
        p_Result_65_fu_650_p4(10) <= ap_const_lv1_1(0);
    end process;

    p_Result_66_fu_694_p4 <= x_l_I_V_36_fu_660_p3(26 downto 18);
    p_Result_67_fu_720_p5 <= (x_l_I_V_36_reg_1543(34 downto 27) & sub_ln202_5_reg_1561 & x_l_I_V_36_reg_1543(17 downto 0));
    
    p_Result_68_fu_730_p4_proc : process(res_I_V_37_reg_1549)
    begin
        p_Result_68_fu_730_p4 <= res_I_V_37_reg_1549;
        p_Result_68_fu_730_p4(9) <= ap_const_lv1_1(0);
    end process;

    p_Result_69_fu_769_p4 <= x_l_I_V_fu_739_p3(25 downto 16);
    p_Result_70_fu_795_p5 <= (x_l_I_V_fu_739_p3(34 downto 26) & sub_ln202_6_fu_789_p2 & x_l_I_V_fu_739_p3(15 downto 0));
    
    p_Result_71_fu_807_p4_proc : process(res_I_V_38_fu_745_p3)
    begin
        p_Result_71_fu_807_p4 <= res_I_V_38_fu_745_p3;
        p_Result_71_fu_807_p4(8) <= ap_const_lv1_1(0);
    end process;

    p_Result_72_fu_851_p4 <= x_l_I_V_37_fu_817_p3(24 downto 14);
    p_Result_73_fu_877_p5 <= (x_l_I_V_37_reg_1566(34 downto 25) & sub_ln202_7_reg_1584 & x_l_I_V_37_reg_1566(13 downto 0));
    
    p_Result_74_fu_887_p4_proc : process(res_I_V_reg_1572)
    begin
        p_Result_74_fu_887_p4 <= res_I_V_reg_1572;
        p_Result_74_fu_887_p4(7) <= ap_const_lv1_1(0);
    end process;

    p_Result_75_fu_926_p4 <= x_l_I_V_38_fu_896_p3(23 downto 12);
    p_Result_76_fu_952_p5 <= (x_l_I_V_38_fu_896_p3(34 downto 24) & sub_ln202_8_fu_946_p2 & x_l_I_V_38_fu_896_p3(11 downto 0));
    
    p_Result_77_fu_964_p4_proc : process(res_I_V_39_fu_902_p3)
    begin
        p_Result_77_fu_964_p4 <= res_I_V_39_fu_902_p3;
        p_Result_77_fu_964_p4(6) <= ap_const_lv1_1(0);
    end process;

    p_Result_78_fu_1008_p4 <= x_l_I_V_39_fu_974_p3(22 downto 10);
    p_Result_79_fu_1034_p5 <= (x_l_I_V_39_fu_974_p3(34 downto 23) & sub_ln202_9_fu_1028_p2 & x_l_I_V_39_fu_974_p3(9 downto 0));
    
    p_Result_80_fu_1046_p4_proc : process(res_I_V_40_fu_982_p3)
    begin
        p_Result_80_fu_1046_p4 <= res_I_V_40_fu_982_p3;
        p_Result_80_fu_1046_p4(5) <= ap_const_lv1_1(0);
    end process;

    p_Result_82_fu_1113_p5 <= (x_l_I_V_40_reg_1589(34 downto 22) & sub_ln202_10_fu_1108_p2 & x_l_I_V_40_reg_1589(7 downto 0));
    
    p_Result_83_fu_1124_p4_proc : process(res_I_V_41_reg_1595)
    begin
        p_Result_83_fu_1124_p4 <= res_I_V_41_reg_1595;
        p_Result_83_fu_1124_p4(4) <= ap_const_lv1_1(0);
    end process;

    p_Result_84_fu_1165_p4 <= x_l_I_V_41_fu_1133_p3(20 downto 6);
    p_Result_85_fu_1191_p5 <= (x_l_I_V_41_fu_1133_p3(34 downto 21) & sub_ln202_11_fu_1185_p2 & x_l_I_V_41_fu_1133_p3(5 downto 0));
    
    p_Result_86_fu_1203_p4_proc : process(res_I_V_42_fu_1140_p3)
    begin
        p_Result_86_fu_1203_p4 <= res_I_V_42_fu_1140_p3;
        p_Result_86_fu_1203_p4(3) <= ap_const_lv1_1(0);
    end process;

    p_Result_88_fu_1270_p5 <= (x_l_I_V_42_reg_1612(34 downto 20) & sub_ln202_12_fu_1265_p2 & x_l_I_V_42_reg_1612(3 downto 0));
    
    p_Result_89_fu_1281_p4_proc : process(res_I_V_43_reg_1618)
    begin
        p_Result_89_fu_1281_p4 <= res_I_V_43_reg_1618;
        p_Result_89_fu_1281_p4(2) <= ap_const_lv1_1(0);
    end process;

    p_Result_8_fu_437_p4 <= res_I_V_34_fu_431_p3(15 downto 12);
    p_Result_90_fu_1322_p4 <= x_l_I_V_43_fu_1290_p3(18 downto 2);
    p_Result_91_fu_1348_p5 <= (x_l_I_V_43_fu_1290_p3(34 downto 19) & sub_ln202_13_fu_1342_p2 & x_l_I_V_43_fu_1290_p3(1 downto 0));
    
    p_Result_92_fu_1360_p4_proc : process(res_I_V_44_fu_1297_p3)
    begin
        p_Result_92_fu_1360_p4 <= res_I_V_44_fu_1297_p3;
        p_Result_92_fu_1360_p4(1) <= ap_const_lv1_1(0);
    end process;

    p_Result_93_fu_1386_p1 <= x_l_I_V_44_fu_1370_p3(18 - 1 downto 0);
    p_Result_94_fu_1418_p5 <= (x_l_I_V_44_reg_1635(34 downto 18) & sub_ln202_14_fu_1413_p2);
    
    p_Result_95_fu_1429_p4_proc : process(res_I_V_45_reg_1641)
    begin
        p_Result_95_fu_1429_p4 <= res_I_V_45_reg_1641;
        p_Result_95_fu_1429_p4(0) <= ap_const_lv1_1(0);
    end process;

    p_Result_s_71_fu_280_p4 <= res_I_V_32_fu_272_p3(15 downto 14);
    p_Result_s_fu_1390_p3 <= x_read_reg_1492_pp0_iter6_reg(31 downto 31);
    res_I_V_30_fu_1470_p2 <= std_logic_vector(unsigned(res_I_V_46_fu_1445_p3) + unsigned(ap_const_lv16_1));
    res_I_V_32_fu_272_p3 <= 
        ap_const_lv16_0 when (icmp_ln443_fu_236_p2(0) = '1') else 
        ap_const_lv16_8000;
    res_I_V_33_fu_354_p3 <= 
        res_I_V_32_fu_272_p3 when (icmp_ln443_1_fu_312_p2(0) = '1') else 
        p_Result_53_fu_336_p4;
    res_I_V_34_fu_431_p3 <= 
        res_I_V_33_reg_1503 when (icmp_ln443_2_reg_1509(0) = '1') else 
        p_Result_56_fu_416_p4;
    res_I_V_35_fu_511_p3 <= 
        res_I_V_34_fu_431_p3 when (icmp_ln443_3_fu_469_p2(0) = '1') else 
        p_Result_59_fu_493_p4;
    res_I_V_36_fu_588_p3 <= 
        res_I_V_35_reg_1526 when (icmp_ln443_4_reg_1532(0) = '1') else 
        p_Result_62_fu_573_p4;
    res_I_V_37_fu_668_p3 <= 
        res_I_V_36_fu_588_p3 when (icmp_ln443_5_fu_626_p2(0) = '1') else 
        p_Result_65_fu_650_p4;
    res_I_V_38_fu_745_p3 <= 
        res_I_V_37_reg_1549 when (icmp_ln443_6_reg_1555(0) = '1') else 
        p_Result_68_fu_730_p4;
    res_I_V_39_fu_902_p3 <= 
        res_I_V_reg_1572 when (icmp_ln443_8_reg_1578(0) = '1') else 
        p_Result_74_fu_887_p4;
    res_I_V_40_fu_982_p3 <= 
        res_I_V_39_fu_902_p3 when (icmp_ln443_9_fu_940_p2(0) = '1') else 
        p_Result_77_fu_964_p4;
    res_I_V_41_fu_1064_p3 <= 
        res_I_V_40_fu_982_p3 when (icmp_ln443_10_fu_1022_p2(0) = '1') else 
        p_Result_80_fu_1046_p4;
    res_I_V_42_fu_1140_p3 <= 
        res_I_V_41_reg_1595 when (icmp_ln443_11_fu_1103_p2(0) = '1') else 
        p_Result_83_fu_1124_p4;
    res_I_V_43_fu_1221_p3 <= 
        res_I_V_42_fu_1140_p3 when (icmp_ln443_12_fu_1179_p2(0) = '1') else 
        p_Result_86_fu_1203_p4;
    res_I_V_44_fu_1297_p3 <= 
        res_I_V_43_reg_1618 when (icmp_ln443_13_fu_1260_p2(0) = '1') else 
        p_Result_89_fu_1281_p4;
    res_I_V_45_fu_1378_p3 <= 
        res_I_V_44_fu_1297_p3 when (icmp_ln443_14_fu_1336_p2(0) = '1') else 
        p_Result_92_fu_1360_p4;
    res_I_V_46_fu_1445_p3 <= 
        res_I_V_45_reg_1641 when (icmp_ln443_15_fu_1408_p2(0) = '1') else 
        p_Result_95_fu_1429_p4;
    res_I_V_47_fu_1476_p3 <= 
        res_I_V_30_fu_1470_p2 when (p_Result_48_fu_1464_p2(0) = '1') else 
        res_I_V_46_fu_1445_p3;
    res_I_V_fu_825_p3 <= 
        res_I_V_38_fu_745_p3 when (icmp_ln443_7_fu_783_p2(0) = '1') else 
        p_Result_71_fu_807_p4;
    select_ln53_fu_1484_p3 <= 
        ap_const_lv16_0 when (p_Result_s_fu_1390_p3(0) = '1') else 
        res_I_V_47_fu_1476_p3;
    sub_ln202_10_fu_1108_p2 <= std_logic_vector(unsigned(p_Result_81_reg_1606) - unsigned(zext_ln443_10_fu_1099_p1));
    sub_ln202_11_fu_1185_p2 <= std_logic_vector(unsigned(p_Result_84_fu_1165_p4) - unsigned(zext_ln443_11_fu_1175_p1));
    sub_ln202_12_fu_1265_p2 <= std_logic_vector(unsigned(p_Result_87_reg_1629) - unsigned(zext_ln443_12_fu_1256_p1));
    sub_ln202_13_fu_1342_p2 <= std_logic_vector(unsigned(p_Result_90_fu_1322_p4) - unsigned(zext_ln443_13_fu_1332_p1));
    sub_ln202_14_fu_1413_p2 <= std_logic_vector(unsigned(p_Result_93_reg_1648) - unsigned(zext_ln443_14_fu_1404_p1));
    sub_ln202_1_fu_400_p2 <= std_logic_vector(unsigned(p_Result_54_fu_380_p4) - unsigned(zext_ln443_1_fu_390_p1));
    sub_ln202_2_fu_475_p2 <= std_logic_vector(unsigned(p_Result_57_fu_455_p4) - unsigned(zext_ln443_2_fu_465_p1));
    sub_ln202_3_fu_557_p2 <= std_logic_vector(unsigned(p_Result_60_fu_537_p4) - unsigned(zext_ln443_3_fu_547_p1));
    sub_ln202_4_fu_632_p2 <= std_logic_vector(unsigned(p_Result_63_fu_612_p4) - unsigned(zext_ln443_4_fu_622_p1));
    sub_ln202_5_fu_714_p2 <= std_logic_vector(unsigned(p_Result_66_fu_694_p4) - unsigned(zext_ln443_5_fu_704_p1));
    sub_ln202_6_fu_789_p2 <= std_logic_vector(unsigned(p_Result_69_fu_769_p4) - unsigned(zext_ln443_6_fu_779_p1));
    sub_ln202_7_fu_871_p2 <= std_logic_vector(unsigned(p_Result_72_fu_851_p4) - unsigned(zext_ln443_7_fu_861_p1));
    sub_ln202_8_fu_946_p2 <= std_logic_vector(unsigned(p_Result_75_fu_926_p4) - unsigned(zext_ln443_8_fu_936_p1));
    sub_ln202_9_fu_1028_p2 <= std_logic_vector(unsigned(p_Result_78_fu_1008_p4) - unsigned(zext_ln443_9_fu_1018_p1));
    sub_ln202_fu_318_p2 <= std_logic_vector(unsigned(p_Result_51_fu_298_p4) - unsigned(zext_ln443_fu_308_p1));
    tmp_10_fu_1092_p3 <= (p_Result_31_reg_1601 & ap_const_lv1_1);
    tmp_11_fu_1157_p3 <= (p_Result_34_fu_1147_p4 & ap_const_lv1_1);
    tmp_12_fu_1249_p3 <= (p_Result_37_reg_1624 & ap_const_lv1_1);
    tmp_13_fu_1314_p3 <= (p_Result_40_fu_1304_p4 & ap_const_lv1_1);
    tmp_14_fu_1397_p3 <= (res_I_V_45_reg_1641 & ap_const_lv1_1);
    tmp_1_fu_290_p3 <= (p_Result_s_71_fu_280_p4 & ap_const_lv1_1);
    tmp_2_fu_372_p3 <= (p_Result_4_fu_362_p4 & ap_const_lv1_1);
    tmp_3_fu_447_p3 <= (p_Result_8_fu_437_p4 & ap_const_lv1_1);
    tmp_4_fu_529_p3 <= (p_Result_10_fu_519_p4 & ap_const_lv1_1);
    tmp_5_fu_604_p3 <= (p_Result_13_fu_594_p4 & ap_const_lv1_1);
    tmp_6_fu_686_p3 <= (p_Result_16_fu_676_p4 & ap_const_lv1_1);
    tmp_7_fu_761_p3 <= (p_Result_19_fu_751_p4 & ap_const_lv1_1);
    tmp_8_fu_843_p3 <= (p_Result_22_fu_833_p4 & ap_const_lv1_1);
    tmp_9_fu_918_p3 <= (p_Result_25_fu_908_p4 & ap_const_lv1_1);
    tmp_fu_226_p4 <= x_int_reg(31 downto 30);
    tmp_s_fu_1000_p3 <= (p_Result_28_fu_990_p4 & ap_const_lv1_1);
    x_l_I_V_31_fu_264_p3 <= 
        zext_ln657_fu_222_p1 when (icmp_ln443_fu_236_p2(0) = '1') else 
        p_Result_50_fu_252_p5;
    x_l_I_V_32_fu_346_p3 <= 
        x_l_I_V_31_fu_264_p3 when (icmp_ln443_1_fu_312_p2(0) = '1') else 
        p_Result_52_fu_324_p5;
    x_l_I_V_33_fu_425_p3 <= 
        x_l_I_V_32_reg_1497 when (icmp_ln443_2_reg_1509(0) = '1') else 
        p_Result_55_fu_406_p5;
    x_l_I_V_34_fu_503_p3 <= 
        x_l_I_V_33_fu_425_p3 when (icmp_ln443_3_fu_469_p2(0) = '1') else 
        p_Result_58_fu_481_p5;
    x_l_I_V_35_fu_582_p3 <= 
        x_l_I_V_34_reg_1520 when (icmp_ln443_4_reg_1532(0) = '1') else 
        p_Result_61_fu_563_p5;
    x_l_I_V_36_fu_660_p3 <= 
        x_l_I_V_35_fu_582_p3 when (icmp_ln443_5_fu_626_p2(0) = '1') else 
        p_Result_64_fu_638_p5;
    x_l_I_V_37_fu_817_p3 <= 
        x_l_I_V_fu_739_p3 when (icmp_ln443_7_fu_783_p2(0) = '1') else 
        p_Result_70_fu_795_p5;
    x_l_I_V_38_fu_896_p3 <= 
        x_l_I_V_37_reg_1566 when (icmp_ln443_8_reg_1578(0) = '1') else 
        p_Result_73_fu_877_p5;
    x_l_I_V_39_fu_974_p3 <= 
        x_l_I_V_38_fu_896_p3 when (icmp_ln443_9_fu_940_p2(0) = '1') else 
        p_Result_76_fu_952_p5;
    x_l_I_V_40_fu_1056_p3 <= 
        x_l_I_V_39_fu_974_p3 when (icmp_ln443_10_fu_1022_p2(0) = '1') else 
        p_Result_79_fu_1034_p5;
    x_l_I_V_41_fu_1133_p3 <= 
        x_l_I_V_40_reg_1589 when (icmp_ln443_11_fu_1103_p2(0) = '1') else 
        p_Result_82_fu_1113_p5;
    x_l_I_V_42_fu_1213_p3 <= 
        x_l_I_V_41_fu_1133_p3 when (icmp_ln443_12_fu_1179_p2(0) = '1') else 
        p_Result_85_fu_1191_p5;
    x_l_I_V_43_fu_1290_p3 <= 
        x_l_I_V_42_reg_1612 when (icmp_ln443_13_fu_1260_p2(0) = '1') else 
        p_Result_88_fu_1270_p5;
    x_l_I_V_44_fu_1370_p3 <= 
        x_l_I_V_43_fu_1290_p3 when (icmp_ln443_14_fu_1336_p2(0) = '1') else 
        p_Result_91_fu_1348_p5;
    x_l_I_V_45_fu_1438_p3 <= 
        x_l_I_V_44_reg_1635 when (icmp_ln443_15_fu_1408_p2(0) = '1') else 
        p_Result_94_fu_1418_p5;
    x_l_I_V_fu_739_p3 <= 
        x_l_I_V_36_reg_1543 when (icmp_ln443_6_reg_1555(0) = '1') else 
        p_Result_67_fu_720_p5;
    zext_ln202_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_226_p4),3));
    zext_ln443_10_fu_1099_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_1092_p3),14));
    zext_ln443_11_fu_1175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_1157_p3),15));
    zext_ln443_12_fu_1256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_1249_p3),16));
    zext_ln443_13_fu_1332_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_1314_p3),17));
    zext_ln443_14_fu_1404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_1397_p3),18));
    zext_ln443_1_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_372_p3),5));
    zext_ln443_2_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_447_p3),6));
    zext_ln443_3_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_529_p3),7));
    zext_ln443_4_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_604_p3),8));
    zext_ln443_5_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_686_p3),9));
    zext_ln443_6_fu_779_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_761_p3),10));
    zext_ln443_7_fu_861_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_843_p3),11));
    zext_ln443_8_fu_936_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_918_p3),12));
    zext_ln443_9_fu_1018_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_1000_p3),13));
    zext_ln443_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_290_p3),4));
    zext_ln657_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_int_reg),35));
    zext_ln662_fu_1460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_I_V_fu_1452_p3),35));
end behav;
