-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ufunc_call_i4_log_32_32_s is
port (
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of ufunc_call_i4_log_32_32_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv31_5 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000101";
    constant ap_const_lv31_D : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000001101";
    constant ap_const_lv31_22 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000100010";
    constant ap_const_lv31_5B : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000001011011";
    constant ap_const_lv31_F5 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000011110101";
    constant ap_const_lv31_29A : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000001010011010";
    constant ap_const_lv31_711 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000011100010001";
    constant ap_const_lv31_1333 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000001001100110011";
    constant ap_const_lv31_3430 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000011010000110000";
    constant ap_const_lv31_8DDC : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000001000110111011100";
    constant ap_const_lv31_1819C : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000011000000110011100";
    constant ap_const_lv31_41832 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000001000001100000110010";
    constant ap_const_lv31_B2149 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000010110010000101001001";
    constant ap_const_lv31_1E4128 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000111100100000100101000";
    constant ap_const_lv31_523D83 : STD_LOGIC_VECTOR (30 downto 0) := "0000000010100100011110110000011";
    constant ap_const_lv31_DF8D60 : STD_LOGIC_VECTOR (30 downto 0) := "0000000110111111000110101100000";
    constant ap_const_lv31_25FAD91 : STD_LOGIC_VECTOR (30 downto 0) := "0000010010111111010110110010001";
    constant ap_const_lv31_673D70C : STD_LOGIC_VECTOR (30 downto 0) := "0000110011100111101011100001100";
    constant ap_const_lv31_118A2AAF : STD_LOGIC_VECTOR (30 downto 0) := "0010001100010100010101010101111";
    constant ap_const_lv31_2FAD89E2 : STD_LOGIC_VECTOR (30 downto 0) := "0101111101011011000100111100010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal select_ln509_cast_fu_324_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_r_V_phi_fu_111_p44 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1451_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_1_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_2_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_3_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_4_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_5_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_6_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_7_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_8_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_9_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_10_fu_252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_11_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_12_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_13_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_14_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_15_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_16_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_17_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_18_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_19_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1451_20_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_188_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal x_s_fu_178_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln1451_21_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_phi_mux_r_V_phi_fu_111_p44_assign_proc : process(select_ln509_cast_fu_324_p3, icmp_ln1451_fu_182_p2, icmp_ln1451_1_fu_198_p2, icmp_ln1451_2_fu_204_p2, icmp_ln1451_3_fu_210_p2, icmp_ln1451_4_fu_216_p2, icmp_ln1451_5_fu_222_p2, icmp_ln1451_6_fu_228_p2, icmp_ln1451_7_fu_234_p2, icmp_ln1451_8_fu_240_p2, icmp_ln1451_9_fu_246_p2, icmp_ln1451_10_fu_252_p2, icmp_ln1451_11_fu_258_p2, icmp_ln1451_12_fu_264_p2, icmp_ln1451_13_fu_270_p2, icmp_ln1451_14_fu_276_p2, icmp_ln1451_15_fu_282_p2, icmp_ln1451_16_fu_288_p2, icmp_ln1451_17_fu_294_p2, icmp_ln1451_18_fu_300_p2, icmp_ln1451_19_fu_306_p2, icmp_ln1451_20_fu_312_p2)
    begin
        if (((icmp_ln1451_20_fu_312_p2 = ap_const_lv1_1) and (icmp_ln1451_19_fu_306_p2 = ap_const_lv1_0) and (icmp_ln1451_18_fu_300_p2 = ap_const_lv1_0) and (icmp_ln1451_17_fu_294_p2 = ap_const_lv1_0) and (icmp_ln1451_16_fu_288_p2 = ap_const_lv1_0) and (icmp_ln1451_15_fu_282_p2 = ap_const_lv1_0) and (icmp_ln1451_14_fu_276_p2 = ap_const_lv1_0) and (icmp_ln1451_13_fu_270_p2 = ap_const_lv1_0) and (icmp_ln1451_12_fu_264_p2 = ap_const_lv1_0) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_13;
        elsif (((icmp_ln1451_19_fu_306_p2 = ap_const_lv1_1) and (icmp_ln1451_18_fu_300_p2 = ap_const_lv1_0) and (icmp_ln1451_17_fu_294_p2 = ap_const_lv1_0) and (icmp_ln1451_16_fu_288_p2 = ap_const_lv1_0) and (icmp_ln1451_15_fu_282_p2 = ap_const_lv1_0) and (icmp_ln1451_14_fu_276_p2 = ap_const_lv1_0) and (icmp_ln1451_13_fu_270_p2 = ap_const_lv1_0) and (icmp_ln1451_12_fu_264_p2 = ap_const_lv1_0) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_12;
        elsif (((icmp_ln1451_18_fu_300_p2 = ap_const_lv1_1) and (icmp_ln1451_17_fu_294_p2 = ap_const_lv1_0) and (icmp_ln1451_16_fu_288_p2 = ap_const_lv1_0) and (icmp_ln1451_15_fu_282_p2 = ap_const_lv1_0) and (icmp_ln1451_14_fu_276_p2 = ap_const_lv1_0) and (icmp_ln1451_13_fu_270_p2 = ap_const_lv1_0) and (icmp_ln1451_12_fu_264_p2 = ap_const_lv1_0) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_11;
        elsif (((icmp_ln1451_17_fu_294_p2 = ap_const_lv1_1) and (icmp_ln1451_16_fu_288_p2 = ap_const_lv1_0) and (icmp_ln1451_15_fu_282_p2 = ap_const_lv1_0) and (icmp_ln1451_14_fu_276_p2 = ap_const_lv1_0) and (icmp_ln1451_13_fu_270_p2 = ap_const_lv1_0) and (icmp_ln1451_12_fu_264_p2 = ap_const_lv1_0) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_10;
        elsif (((icmp_ln1451_16_fu_288_p2 = ap_const_lv1_1) and (icmp_ln1451_15_fu_282_p2 = ap_const_lv1_0) and (icmp_ln1451_14_fu_276_p2 = ap_const_lv1_0) and (icmp_ln1451_13_fu_270_p2 = ap_const_lv1_0) and (icmp_ln1451_12_fu_264_p2 = ap_const_lv1_0) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_F;
        elsif (((icmp_ln1451_15_fu_282_p2 = ap_const_lv1_1) and (icmp_ln1451_14_fu_276_p2 = ap_const_lv1_0) and (icmp_ln1451_13_fu_270_p2 = ap_const_lv1_0) and (icmp_ln1451_12_fu_264_p2 = ap_const_lv1_0) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_E;
        elsif (((icmp_ln1451_14_fu_276_p2 = ap_const_lv1_1) and (icmp_ln1451_13_fu_270_p2 = ap_const_lv1_0) and (icmp_ln1451_12_fu_264_p2 = ap_const_lv1_0) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_D;
        elsif (((icmp_ln1451_13_fu_270_p2 = ap_const_lv1_1) and (icmp_ln1451_12_fu_264_p2 = ap_const_lv1_0) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_C;
        elsif (((icmp_ln1451_12_fu_264_p2 = ap_const_lv1_1) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_B;
        elsif (((icmp_ln1451_11_fu_258_p2 = ap_const_lv1_1) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_A;
        elsif (((icmp_ln1451_10_fu_252_p2 = ap_const_lv1_1) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_9;
        elsif (((icmp_ln1451_9_fu_246_p2 = ap_const_lv1_1) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_8;
        elsif (((icmp_ln1451_8_fu_240_p2 = ap_const_lv1_1) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_7;
        elsif (((icmp_ln1451_7_fu_234_p2 = ap_const_lv1_1) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_6;
        elsif (((icmp_ln1451_6_fu_228_p2 = ap_const_lv1_1) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_5;
        elsif (((icmp_ln1451_5_fu_222_p2 = ap_const_lv1_1) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_4;
        elsif (((icmp_ln1451_4_fu_216_p2 = ap_const_lv1_1) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_3;
        elsif (((icmp_ln1451_3_fu_210_p2 = ap_const_lv1_1) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_2;
        elsif (((icmp_ln1451_2_fu_204_p2 = ap_const_lv1_1) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_1;
        elsif (((icmp_ln1451_1_fu_198_p2 = ap_const_lv1_1) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_0;
        elsif ((icmp_ln1451_fu_182_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= ap_const_lv32_80000000;
        elsif (((icmp_ln1451_20_fu_312_p2 = ap_const_lv1_0) and (icmp_ln1451_19_fu_306_p2 = ap_const_lv1_0) and (icmp_ln1451_18_fu_300_p2 = ap_const_lv1_0) and (icmp_ln1451_17_fu_294_p2 = ap_const_lv1_0) and (icmp_ln1451_16_fu_288_p2 = ap_const_lv1_0) and (icmp_ln1451_15_fu_282_p2 = ap_const_lv1_0) and (icmp_ln1451_14_fu_276_p2 = ap_const_lv1_0) and (icmp_ln1451_13_fu_270_p2 = ap_const_lv1_0) and (icmp_ln1451_12_fu_264_p2 = ap_const_lv1_0) and (icmp_ln1451_11_fu_258_p2 = ap_const_lv1_0) and (icmp_ln1451_10_fu_252_p2 = ap_const_lv1_0) and (icmp_ln1451_9_fu_246_p2 = ap_const_lv1_0) and (icmp_ln1451_8_fu_240_p2 = ap_const_lv1_0) and (icmp_ln1451_7_fu_234_p2 = ap_const_lv1_0) and (icmp_ln1451_6_fu_228_p2 = ap_const_lv1_0) and (icmp_ln1451_5_fu_222_p2 = ap_const_lv1_0) and (icmp_ln1451_4_fu_216_p2 = ap_const_lv1_0) and (icmp_ln1451_3_fu_210_p2 = ap_const_lv1_0) and (icmp_ln1451_2_fu_204_p2 = ap_const_lv1_0) and (icmp_ln1451_1_fu_198_p2 = ap_const_lv1_0) and (icmp_ln1451_fu_182_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_r_V_phi_fu_111_p44 <= select_ln509_cast_fu_324_p3;
        else 
            ap_phi_mux_r_V_phi_fu_111_p44 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return <= ap_phi_mux_r_V_phi_fu_111_p44;
    icmp_ln1451_10_fu_252_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_3430)) else "0";
    icmp_ln1451_11_fu_258_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_8DDC)) else "0";
    icmp_ln1451_12_fu_264_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_1819C)) else "0";
    icmp_ln1451_13_fu_270_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_41832)) else "0";
    icmp_ln1451_14_fu_276_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_B2149)) else "0";
    icmp_ln1451_15_fu_282_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_1E4128)) else "0";
    icmp_ln1451_16_fu_288_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_523D83)) else "0";
    icmp_ln1451_17_fu_294_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_DF8D60)) else "0";
    icmp_ln1451_18_fu_300_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_25FAD91)) else "0";
    icmp_ln1451_19_fu_306_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_673D70C)) else "0";
    icmp_ln1451_1_fu_198_p2 <= "1" when (tmp_fu_188_p4 = ap_const_lv30_0) else "0";
    icmp_ln1451_20_fu_312_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_118A2AAF)) else "0";
    icmp_ln1451_21_fu_318_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_2FAD89E2)) else "0";
    icmp_ln1451_2_fu_204_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_5)) else "0";
    icmp_ln1451_3_fu_210_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_D)) else "0";
    icmp_ln1451_4_fu_216_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_22)) else "0";
    icmp_ln1451_5_fu_222_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_5B)) else "0";
    icmp_ln1451_6_fu_228_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_F5)) else "0";
    icmp_ln1451_7_fu_234_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_29A)) else "0";
    icmp_ln1451_8_fu_240_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_711)) else "0";
    icmp_ln1451_9_fu_246_p2 <= "1" when (unsigned(x_s_fu_178_p1) < unsigned(ap_const_lv31_1333)) else "0";
    icmp_ln1451_fu_182_p2 <= "1" when (signed(x) < signed(ap_const_lv32_1)) else "0";
    select_ln509_cast_fu_324_p3 <= 
        ap_const_lv32_14 when (icmp_ln1451_21_fu_318_p2(0) = '1') else 
        ap_const_lv32_15;
    tmp_fu_188_p4 <= x(30 downto 1);
    x_s_fu_178_p1 <= x(31 - 1 downto 0);
end behav;
