// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ufunc_call_f4_addsub_0_0_ap_fixed_39_2_5_3_0_ap_fixed_39_2_5_3_0_ap_uint_1_s (
        ap_ready,
        a,
        b,
        add,
        ap_return
);


output   ap_ready;
input  [38:0] a;
input  [36:0] b;
input  [0:0] add;
output  [38:0] ap_return;

wire   [38:0] zext_ln1147_fu_36_p1;
wire   [38:0] ret_V_14_fu_46_p2;
wire   [38:0] ret_V_fu_40_p2;

assign ap_ready = 1'b1;

assign ap_return = ((add[0:0] == 1'b1) ? ret_V_14_fu_46_p2 : ret_V_fu_40_p2);

assign ret_V_14_fu_46_p2 = (zext_ln1147_fu_36_p1 + a);

assign ret_V_fu_40_p2 = (a - zext_ln1147_fu_36_p1);

assign zext_ln1147_fu_36_p1 = b;

endmodule //ufunc_call_f4_addsub_0_0_ap_fixed_39_2_5_3_0_ap_fixed_39_2_5_3_0_ap_uint_1_s
