// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ufunc_call_i4_log_32_32_s (
        ap_ready,
        x,
        ap_return
);


output   ap_ready;
input  [31:0] x;
output  [31:0] ap_return;

wire   [31:0] select_ln509_cast_fu_324_p3;
reg   [31:0] ap_phi_mux_r_V_phi_fu_111_p44;
wire   [0:0] icmp_ln1451_fu_182_p2;
wire   [0:0] icmp_ln1451_1_fu_198_p2;
wire   [0:0] icmp_ln1451_2_fu_204_p2;
wire   [0:0] icmp_ln1451_3_fu_210_p2;
wire   [0:0] icmp_ln1451_4_fu_216_p2;
wire   [0:0] icmp_ln1451_5_fu_222_p2;
wire   [0:0] icmp_ln1451_6_fu_228_p2;
wire   [0:0] icmp_ln1451_7_fu_234_p2;
wire   [0:0] icmp_ln1451_8_fu_240_p2;
wire   [0:0] icmp_ln1451_9_fu_246_p2;
wire   [0:0] icmp_ln1451_10_fu_252_p2;
wire   [0:0] icmp_ln1451_11_fu_258_p2;
wire   [0:0] icmp_ln1451_12_fu_264_p2;
wire   [0:0] icmp_ln1451_13_fu_270_p2;
wire   [0:0] icmp_ln1451_14_fu_276_p2;
wire   [0:0] icmp_ln1451_15_fu_282_p2;
wire   [0:0] icmp_ln1451_16_fu_288_p2;
wire   [0:0] icmp_ln1451_17_fu_294_p2;
wire   [0:0] icmp_ln1451_18_fu_300_p2;
wire   [0:0] icmp_ln1451_19_fu_306_p2;
wire   [0:0] icmp_ln1451_20_fu_312_p2;
wire   [29:0] tmp_fu_188_p4;
wire   [30:0] x_s_fu_178_p1;
wire   [0:0] icmp_ln1451_21_fu_318_p2;
wire    ap_ce_reg;

always @ (*) begin
    if (((icmp_ln1451_20_fu_312_p2 == 1'd1) & (icmp_ln1451_19_fu_306_p2 == 1'd0) & (icmp_ln1451_18_fu_300_p2 == 1'd0) & (icmp_ln1451_17_fu_294_p2 == 1'd0) & (icmp_ln1451_16_fu_288_p2 == 1'd0) & (icmp_ln1451_15_fu_282_p2 == 1'd0) & (icmp_ln1451_14_fu_276_p2 == 1'd0) & (icmp_ln1451_13_fu_270_p2 == 1'd0) & (icmp_ln1451_12_fu_264_p2 == 1'd0) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd19;
    end else if (((icmp_ln1451_19_fu_306_p2 == 1'd1) & (icmp_ln1451_18_fu_300_p2 == 1'd0) & (icmp_ln1451_17_fu_294_p2 == 1'd0) & (icmp_ln1451_16_fu_288_p2 == 1'd0) & (icmp_ln1451_15_fu_282_p2 == 1'd0) & (icmp_ln1451_14_fu_276_p2 == 1'd0) & (icmp_ln1451_13_fu_270_p2 == 1'd0) & (icmp_ln1451_12_fu_264_p2 == 1'd0) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd18;
    end else if (((icmp_ln1451_18_fu_300_p2 == 1'd1) & (icmp_ln1451_17_fu_294_p2 == 1'd0) & (icmp_ln1451_16_fu_288_p2 == 1'd0) & (icmp_ln1451_15_fu_282_p2 == 1'd0) & (icmp_ln1451_14_fu_276_p2 == 1'd0) & (icmp_ln1451_13_fu_270_p2 == 1'd0) & (icmp_ln1451_12_fu_264_p2 == 1'd0) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd17;
    end else if (((icmp_ln1451_17_fu_294_p2 == 1'd1) & (icmp_ln1451_16_fu_288_p2 == 1'd0) & (icmp_ln1451_15_fu_282_p2 == 1'd0) & (icmp_ln1451_14_fu_276_p2 == 1'd0) & (icmp_ln1451_13_fu_270_p2 == 1'd0) & (icmp_ln1451_12_fu_264_p2 == 1'd0) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd16;
    end else if (((icmp_ln1451_16_fu_288_p2 == 1'd1) & (icmp_ln1451_15_fu_282_p2 == 1'd0) & (icmp_ln1451_14_fu_276_p2 == 1'd0) & (icmp_ln1451_13_fu_270_p2 == 1'd0) & (icmp_ln1451_12_fu_264_p2 == 1'd0) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd15;
    end else if (((icmp_ln1451_15_fu_282_p2 == 1'd1) & (icmp_ln1451_14_fu_276_p2 == 1'd0) & (icmp_ln1451_13_fu_270_p2 == 1'd0) & (icmp_ln1451_12_fu_264_p2 == 1'd0) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd14;
    end else if (((icmp_ln1451_14_fu_276_p2 == 1'd1) & (icmp_ln1451_13_fu_270_p2 == 1'd0) & (icmp_ln1451_12_fu_264_p2 == 1'd0) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd13;
    end else if (((icmp_ln1451_13_fu_270_p2 == 1'd1) & (icmp_ln1451_12_fu_264_p2 == 1'd0) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd12;
    end else if (((icmp_ln1451_12_fu_264_p2 == 1'd1) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd11;
    end else if (((icmp_ln1451_11_fu_258_p2 == 1'd1) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd10;
    end else if (((icmp_ln1451_10_fu_252_p2 == 1'd1) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd9;
    end else if (((icmp_ln1451_9_fu_246_p2 == 1'd1) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd8;
    end else if (((icmp_ln1451_8_fu_240_p2 == 1'd1) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd7;
    end else if (((icmp_ln1451_7_fu_234_p2 == 1'd1) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd6;
    end else if (((icmp_ln1451_6_fu_228_p2 == 1'd1) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd5;
    end else if (((icmp_ln1451_5_fu_222_p2 == 1'd1) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd4;
    end else if (((icmp_ln1451_4_fu_216_p2 == 1'd1) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd3;
    end else if (((icmp_ln1451_3_fu_210_p2 == 1'd1) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd2;
    end else if (((icmp_ln1451_2_fu_204_p2 == 1'd1) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd1;
    end else if (((icmp_ln1451_1_fu_198_p2 == 1'd1) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd0;
    end else if ((icmp_ln1451_fu_182_p2 == 1'd1)) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 32'd2147483648;
    end else if (((icmp_ln1451_20_fu_312_p2 == 1'd0) & (icmp_ln1451_19_fu_306_p2 == 1'd0) & (icmp_ln1451_18_fu_300_p2 == 1'd0) & (icmp_ln1451_17_fu_294_p2 == 1'd0) & (icmp_ln1451_16_fu_288_p2 == 1'd0) & (icmp_ln1451_15_fu_282_p2 == 1'd0) & (icmp_ln1451_14_fu_276_p2 == 1'd0) & (icmp_ln1451_13_fu_270_p2 == 1'd0) & (icmp_ln1451_12_fu_264_p2 == 1'd0) & (icmp_ln1451_11_fu_258_p2 == 1'd0) & (icmp_ln1451_10_fu_252_p2 == 1'd0) & (icmp_ln1451_9_fu_246_p2 == 1'd0) & (icmp_ln1451_8_fu_240_p2 == 1'd0) & (icmp_ln1451_7_fu_234_p2 == 1'd0) & (icmp_ln1451_6_fu_228_p2 == 1'd0) & (icmp_ln1451_5_fu_222_p2 == 1'd0) & (icmp_ln1451_4_fu_216_p2 == 1'd0) & (icmp_ln1451_3_fu_210_p2 == 1'd0) & (icmp_ln1451_2_fu_204_p2 == 1'd0) & (icmp_ln1451_1_fu_198_p2 == 1'd0) & (icmp_ln1451_fu_182_p2 == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_111_p44 = select_ln509_cast_fu_324_p3;
    end else begin
        ap_phi_mux_r_V_phi_fu_111_p44 = 'bx;
    end
end

assign ap_ready = 1'b1;

assign ap_return = ap_phi_mux_r_V_phi_fu_111_p44;

assign icmp_ln1451_10_fu_252_p2 = ((x_s_fu_178_p1 < 31'd13360) ? 1'b1 : 1'b0);

assign icmp_ln1451_11_fu_258_p2 = ((x_s_fu_178_p1 < 31'd36316) ? 1'b1 : 1'b0);

assign icmp_ln1451_12_fu_264_p2 = ((x_s_fu_178_p1 < 31'd98716) ? 1'b1 : 1'b0);

assign icmp_ln1451_13_fu_270_p2 = ((x_s_fu_178_p1 < 31'd268338) ? 1'b1 : 1'b0);

assign icmp_ln1451_14_fu_276_p2 = ((x_s_fu_178_p1 < 31'd729417) ? 1'b1 : 1'b0);

assign icmp_ln1451_15_fu_282_p2 = ((x_s_fu_178_p1 < 31'd1982760) ? 1'b1 : 1'b0);

assign icmp_ln1451_16_fu_288_p2 = ((x_s_fu_178_p1 < 31'd5389699) ? 1'b1 : 1'b0);

assign icmp_ln1451_17_fu_294_p2 = ((x_s_fu_178_p1 < 31'd14650720) ? 1'b1 : 1'b0);

assign icmp_ln1451_18_fu_300_p2 = ((x_s_fu_178_p1 < 31'd39824785) ? 1'b1 : 1'b0);

assign icmp_ln1451_19_fu_306_p2 = ((x_s_fu_178_p1 < 31'd108254988) ? 1'b1 : 1'b0);

assign icmp_ln1451_1_fu_198_p2 = ((tmp_fu_188_p4 == 30'd0) ? 1'b1 : 1'b0);

assign icmp_ln1451_20_fu_312_p2 = ((x_s_fu_178_p1 < 31'd294267567) ? 1'b1 : 1'b0);

assign icmp_ln1451_21_fu_318_p2 = ((x_s_fu_178_p1 < 31'd799902178) ? 1'b1 : 1'b0);

assign icmp_ln1451_2_fu_204_p2 = ((x_s_fu_178_p1 < 31'd5) ? 1'b1 : 1'b0);

assign icmp_ln1451_3_fu_210_p2 = ((x_s_fu_178_p1 < 31'd13) ? 1'b1 : 1'b0);

assign icmp_ln1451_4_fu_216_p2 = ((x_s_fu_178_p1 < 31'd34) ? 1'b1 : 1'b0);

assign icmp_ln1451_5_fu_222_p2 = ((x_s_fu_178_p1 < 31'd91) ? 1'b1 : 1'b0);

assign icmp_ln1451_6_fu_228_p2 = ((x_s_fu_178_p1 < 31'd245) ? 1'b1 : 1'b0);

assign icmp_ln1451_7_fu_234_p2 = ((x_s_fu_178_p1 < 31'd666) ? 1'b1 : 1'b0);

assign icmp_ln1451_8_fu_240_p2 = ((x_s_fu_178_p1 < 31'd1809) ? 1'b1 : 1'b0);

assign icmp_ln1451_9_fu_246_p2 = ((x_s_fu_178_p1 < 31'd4915) ? 1'b1 : 1'b0);

assign icmp_ln1451_fu_182_p2 = (($signed(x) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign select_ln509_cast_fu_324_p3 = ((icmp_ln1451_21_fu_318_p2[0:0] == 1'b1) ? 32'd20 : 32'd21);

assign tmp_fu_188_p4 = {{x[30:1]}};

assign x_s_fu_178_p1 = x[30:0];

endmodule //ufunc_call_i4_log_32_32_s
